# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Format
        run: |
          swiftformat --verbose .
          git diff --exit-code
          if [ $? -eq 0 ]; then
            echo "No changes after formatting"
          else
            echo "Changes after formatting. Please run swiftformat locally and commit changes."
            exit 1
          fi
      - name: Lint
        run: swiftlint lint --strict
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Install dependencies
        run: cd fixtures && make prepare
      - name: Generate fixtures
        run: cd fixtures && make generate
      - name: Build
        run: swift build
      - name: Run tests (Unit)
        run: swift test

  end-to-end-testing:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Install buildifier
        run: |
          brew install buildifier
          buildifier --version
      - name: Install dependencies
        run: cd fixtures && make prepare
      - name: Generate fixtures
        run: cd fixtures && make generate
      - name: Build (debug)
        run: swift build -c debug
      - name: Bazel generation
        run: |
          brew install bazelisk
          cd fixtures/basic
          ../../.build/debug/xcode-migrate bazel -p ./BasicFixtureProject.xcodeproj
      - name: Git diff
        run: |
          git diff --exit-code
          if [ $? -eq 0 ]; then
            echo "No changes after bazel testing"
          else
            echo "Changes after bazel testing. Please run xcode-migrate locally and commit changes."
            exit 1
          fi
      - name: Build using Bazel
        run: |
          cd fixtures/basic
          bazel build //:BasicFixtureProject --sandbox_debug --verbose_failures
