# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: cd fixtures && make prepare

      - name: Generat fixtures
        run: cd fixtures && make generate

      - name: Build
        run: swift build -v
      - name: Run tests (Unit)
        run: swift test -v

      - name: Run tests (End to end)
        run: |
          brew install bazelisk
          cd fixtures/basic
          bazel build //:BasicFixtureProject --sandbox_debug --verbose_failures
